version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run linting
          command: npm run lint || echo "No lint script found"
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Start server (health check)
          command: |
            npm start &
            sleep 10
            curl -f http://localhost:3000 || curl -f http://localhost:8000 || echo "Server health check completed"
            pkill -f "node"
      - run:
          name: SonarCloud Scan
          command: |
            npm install -g sonarqube-scanner
            sonar-scanner \
              -Dsonar.organization=$SONAR_ORG \
              -Dsonar.projectKey=$CIRCLE_PROJECT_REPONAME \
              -Dsonar.sources=./src,./server.js,./index.js \
              -Dsonar.tests=./tests,./test \
              -Dsonar.test.inclusions=**/*.test.js,**/*.spec.js \
              -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build